---
- name: Install packages required by virtualbmc
  become: true
  package:
    name:
      - python3-pip
      - python3-setuptools
      - python3-devel
      - libvirt-devel
      - gcc
      - ipmitool
      - libvirt-client

- name: Upgrade pip
  become: true
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade
    state: latest

- name: Install virtualbmc
  become: true
  pip:
    name: virtualbmc
    executable: pip3

- name: Create directories needed by vbmc if it does not exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/virtualbmc
    - /var/log/virtualbmc

- name: Copy the vbmc configuration file
  become: true
  copy:
    src: virtualbmc.conf
    dest: /etc/virtualbmc

- name: Add VirtualBMC as systemd service
  become: true
  copy:
    mode: 0664
    src: virtualbmc.service
    dest: "/etc/systemd/system/virtualbmc.service"

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Start VirtualBMC
  become: true
  systemd:
    name: virtualbmc
    state: started
    enabled: yes
