services:
#  tftpboot:
#    image: tftpgoteam/hooktftp
#    ports:
#      - '69:69'
#    volumes:
#      - ./tftpboot/data:/var/lib/tftpboot
#      - ./tftpboot/config/hooktftp.yml:/etc/hooktftp.yml
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  bkr-api:
    build:
      context: .
      dockerfile: Containerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      REDIS_HOST: redis
      BACKEND_PORT: 8001
    ports:
      - '8001:8001'
    volumes:
      - .:/code
    depends_on:
      - redis
  lab-api:
    build:
      context: .
      dockerfile: Containerfile-lab-api
    stop_signal: SIGINT
    environment:
      REDIS_HOST: redis
      LAB_PORT: 8081
    ports:
      - '8081:8081'
    depends_on:
      - redis
  lab-worker:
    build:
      context: .
      dockerfile: Containerfile-lab-worker
    environment:
      RQ_QUEUE: lab1
      REDIS_HOST: redis
    volumes:
      - ./tftpboot/data:/opt/tftpboot/data
    depends_on:
      - redis
