#!/bin/bash

DEFAULT_NETBOOT_TEMPLATES=${DEFAULT_TEMPLATES:=/opt/dci-provisioner/templates/netboot/}
TEMPLATE_NETBOOT_DIR=${TEMPLATE_NETBOOT_DIR:=/opt/templates/netboot}
DEFAULT_KICKSTART_TEMPLATES=${DEFAULT_TEMPLATES:=/opt/dci-provisioner/templates/kickstarts/}
TEMPLATE_KICKSTART_DIR=${TEMPLATE_KICKSTART_DIR:=/opt/templates/kickstarts}
DEFAULT_NETBOOT_IMAGES=${DEFAULT_NETBOOT_IMAGES:=/opt/dci-provisioner/netboot_images/}
NETBOOT_IMAGES_DIR=${NETBOOT_IMAGES_DIR:=/opt/tftpboot}

mkdir -p $TEMPLATE_NETBOOT_DIR
mkdir -p $TEMPLATE_KICKSTART_DIR
mkdir -p $NETBOOT_IMAGES_DIR

# Only copy default netboot template if it's missing.
for FILE in $DEFAULT_TEMPLATES/*; do
	TEMPLATE=${FILE#$DEFAULT_NETBOOT_TEMPLATES/}
	if [ ! -e "$TEMPLATE_NETBOOT_DIR/$TEMPLATE" ]; then
		cp $DEFAULT_NETBOOT_TEMPLATES/$TEMPLATE $TEMPLATE_NETBOOT_DIR/$TEMPLATE
	fi
done

# Only copy default kickstart template if it's missing.
for FILE in $DEFAULT_KICKSTART_TEMPLATES/*; do
	TEMPLATE=${FILE#$DEFAULT_KICKSTART_TEMPLATES/}
	if [ ! -e "$TEMPLATE_KICKSTART_DIR/$TEMPLATE" ]; then
		cp $DEFAULT_KICKSTART_TEMPLATES/$TEMPLATE $TEMPLATE_KICKSTART_DIR/$TEMPLATE
	fi
done

# Only copy default netboot images if it's missing.
for FILE in $DEFAULT_NETBOOT_IMAGES/*; do
	NETBOOT_IMAGE=${FILE#$DEFAULT_NETBOOT_IMAGES/}
	if [ ! -e "$NETBOOT_IMAGES_DIR/$NETBOOT_IMAGE" ]; then
		cp $DEFAULT_NETBOOT_IMAGES/$NETBOOT_IMAGE $NETBOOT_IMAGES_DIR/$NETBOOT_IMAGE
	fi
done

exec "$@"
