---
- name: Provision Node
  block:
    - name: Create rng device XML file
      template:
        src: rng_device.xml.j2
        dest: "{{ temp_dir.path }}/rng_device.xml"
        mode: 0664

    - name: Copy nvram for System to Support EFI Boot
      copy:
        src: /usr/share/edk2/ovmf/OVMF_VARS.fd
        dest: /var/lib/libvirt/qemu/nvram/{{ inventory_hostname }}_VARS.fd
        mode: 0755
        remote_src: true
      when:
        - virt is defined
        - virt.mode| default('') == 'efi'

    - name: Create vm creation_script
      template:
        # community.libvirt.virt doesn't define the qcow image so it was chosen to use
        # virt-install. The reason we use a script is to aid with debugging on the host
        src: create_vm.sh.j2
        dest: "{{ temp_dir.path }}/{{ inventory_hostname }}_setup_vm.sh"
        lstrip_blocks: true
        mode: 0774
      when:
        - virt is defined

    - name: Run vm creation_script
      shell: 
        cmd: "/bin/bash {{ temp_dir.path }}/{{ inventory_hostname }}_setup_vm.sh"
      when:
        - virt is defined

