FROM quay.io/fedora/s2i-core:latest

ENV LANG en_US.UTF-8

VOLUME /var/lib/tftpboot

RUN dnf -y upgrade && \
    rpm --setcaps shadow-utils 2>/dev/null && \
    dnf -y install python3 python3-pip supervisor ipmitool fence-agents-lpar && \
    dnf clean all

COPY api /opt/dci-provisioner/api
COPY requirements.txt \
     run_worker.sh \
     /opt/dci-provisioner
COPY templates /opt/dci-provisioner/templates
COPY configs/supervisord.d/dci-lab.ini \
     configs/supervisord.d/rq_worker.ini \
     /etc/supervisord.d
COPY entrypoint.sh /opt/dci-provisioner/entrypoint.sh
COPY files/power_scripts /etc/power-scripts
COPY files/netboot_images /opt/dci-provisioner/netboot_images

WORKDIR /opt/dci-provisioner
RUN pip install -r requirements.txt

ENV PYTHONPATH /opt/dci-provisioner

ENTRYPOINT ["/opt/dci-provisioner/entrypoint.sh"]

CMD ["supervisord", "-n"]

