---
- name: Generate /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: '{{ item.value.ip_address }} {{ item.key.split(".")| first }} {{ item.key.split(".")| first }}.{{ domain }}'
  loop: "{{ q('dict', lab.system_inventory | default({})| combine({jumpbox: {'ip_address': machine_network_ip| default(local_repo_ip) }})) }}"

- name: Update provisioner.conf file
  template:
    src: provisioner.conf.j2
    dest: /etc/dnsmasq.d/provisioner.conf
  register: dns_conf_update

- name: Make sure dnsmasq is enabled
  ansible.builtin.systemd:
    name: dnsmasq
    state: started
    enabled: true

- name: Restart dnsmasq if any config files were changed
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
  when: dns_conf_update.changed | default('false') | bool
